### ISSUE TITLE
Further explanation

### ISSUE THREAD

**Issue by nelsonjd** [BOAKGP/CTF-Writeups#1]
Hi, thanks for the writeup.
Can you explain how you did this? 

> We have to redirect output to file and then remove unnecessary lines added by this application (menu etc.) This way we got the copy of the binary running on the server.

**Comment by 0e85dc6eaf** [comment]
Sure.
```
printf "2\n../main\n3\n" | nc mngmnt-iface.ctfcompetition.com 1337 > output.bin
```
But everything that was sent by server is redirected to output.bin, not only the binary.
So we need to manually remove those additional lines to make it valid elf.
(so everything before \x7fELF and after the series of null bytes at the end)

I attached output.zip containing both output.bin (raw response) and output (removed unnecessary data, it's dump.elf from repository )
[output.zip](https://github.com/BOAKGP/CTF-Writeups/files/2150616/output.zip)

**Comment by nelsonjd** [comment]
Thanks for the explanation.  I'm a beginner so these tasks are new to me.  I'm having some issues using vim to remove bytes (even in the vim hex viewer mode).  Every time I save it corrupts bytes.  I'm going to use dd to remove bytes at the beginning of the file.

**Comment by 0e85dc6eaf** [comment]
I used Notepad++ to remove this data, but now I tried with vim and it works too. Do you know which bytes got corrupted? You can't run the application at all or it crashes later?

**Comment by nelsonjd** [comment]
Thanks, I got the .elf.  I had to fiddle with vim a bit to figure out how to use the hex mode.  For example, make sure I switch back out of hex mode before :w  😄
